services:
  postgres:
    image: postgres:16
    restart: always
    container_name: user-management-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: user-management-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile # Verifique se o caminho do arquivo está correto
    container_name: user-management-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      REDIS_URL: "redis://redis:6379"
      NODE_ENV: development
      JWT_SECRET: "HkG+0L60Hn1s1+NpYnbvawKnCvk2S6ziZNNwTdiFym8="
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app # Volume para refletir mudanças de código em tempo real (opcional)

volumes:
  pgdata:
